name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Compile
      run: mvn clean compile
    - name: Package
      run: mvn package  # 添加打包命令
    - name: Test
      run: mvn test
    - name: Create artifact directory
      run: mkdir -p artifacts
    # 将编译后的类文件复制到临时目录
    - name: Copy compiled classes
      run: cp -r target/classes artifacts/
    # 将测试报告（以Surefire为例）复制到临时目录，不同测试框架报告位置可能不同，按需调整
    - name: Copy test reports
      run: cp -r target/surefire-reports artifacts/
    # 将生成的jar包复制到临时目录
    - name: Copy jar file
      run: cp target/*.jar artifacts/  # 假设jar包在target目录下，根据实际情况调整
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: java-project-artifacts
        path: artifacts
